language: ruby
before_install:
  - 'if [[ "$TRAVIS_RUBY_VERSION" =~ "jruby" ]] ; then gem update --system ; fi'
before_script:
  - 'if [[ "$DB" =~ "postgresql" ]] ; then cp config/database.yml.postgresql config/database.yml ; psql -c "create database devpay_database_test;" -U postgres ; fi'
  - 'if [[ "$DB" =~ "mysql" ]] ; then cp config/database.yml.mysql config/database.yml ; mysql -e "create database your_test_database;" ; fi'
  - bundle exec rake db:schema:load
  - 'rake db:test:prepare'
  - 'mkdir -p tmp/cache'
  - 'sh -e /etc/init.d/xvfb start'
script:
  - 'DISPLAY=:99.0 bundle exec rspec ./spec'
notifications:
  email: true
env:
  - DB=postgresql
  - DB=mysql
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
rvm:
  - ree
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
